services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Clickstorm\CsPowermailGdpr\:
    resource: '../Classes/*'

  Clickstorm\CsPowermailGdpr\EventListener\FormControllerCreateActionBeforeRenderViewEventListener:
    tags:
      - name: event.listener
        identifier: 'csPowermailGdprFormControllerCreateActionBeforeRenderViewEventListener'
        event: In2code\Powermail\Events\FormControllerCreateActionBeforeRenderViewEvent
